### ISSUE TITLE
Support for Nexa transmitters?

### ISSUE THREAD

**Issue by wilenius** [vinnyspb/nexa-controller-rpi#1]
Hi, do you reckon it would be difficult/time consuming to add support for Nexa transmitters like this one? 

http://www.clasohlson.com/se/R%C3%B6relsevakt-utomhus-Nexa-LMDT-810/Pr364914000

**Comment by vinnyspb** [comment]
Hi, I believe this is the one I use right now. Doesn't the code work for you?

**Comment by wilenius** [comment]
Oh, cool, I though the code was just for transmitting on/off info to the remote electrical sockets, not for receiving info. Sorry about that! I'm just about to buy the Nexa components, and I was wondering which ones would work with your code. Thanks for a quick reply!

**Comment by vinnyspb** [comment]
I probably misunderstood your first comment. For decoding signal from Nexa transmitters you might want to look into here: https://github.com/vinnyspb/ook-decoder

I used DVB-T stick & raspberry pi for that.

**Comment by wilenius** [comment]
Ok, maybe I'll just go with the Nexa remote sockets and get a motion detector that has support out of the box, like this one: http://ha.privateeyepi.com/store/index.php?route=product/product&product_id=76. Thanks again!
