### ISSUE TITLE
TX443N transmission problem

### ISSUE THREAD

**Issue by JanneHonkonen** [vinnyspb/nexa-controller-rpi#2]
I have a problem with a question of my TX443N and with nexa-controller-rpi. This might not be an issue with this project, but with a hardware but since I am not familiar with setup, I'll post this an as issue here.

I recently got my hands on TX443N and setup proper wiring, noticing two things: First, manual_switch.py using I was unable control or register to my Nexa Outlets (Date code: 1603) and second, TX443N caused radio interference to any other Nexa (remote controls (Date code: 1603 also) in the ~10-20 meters area preventing them working.

I have triple-checked wiring and circuit, so could this problem be of a faulty TX443N or is this some sort antenna-issue. I have tried varying length on 15 to 30 cm (optimal calculated is ~30cm).

I am running most recent rasbian on a Raspberry Pi 3. Any clues or experience of similar problems?

**Comment by vinnyspb** [comment]
I assume that TX443N is some kind of 443.92Mhz transmitter? Can't find the specs on the internet.
Per my experience, the interference with other devices was always a symptom of constant transmission on that frequency, that said, data pin is always in "1" state or incorrectly powered transmitter.

Also please check that you use correct GPIO PIN numbering scheme - in this project scripts expect physical numbers, not GPIO numbers: https://www.element14.com/community/servlet/JiveServlet/previewBody/73950-102-10-339300/pi3_gpio.png

Regarding antenna, my setup works fine without any antenna at all, but the distance is only about 2 meters.

**Comment by hermanil** [comment]
Vinny thank you for sharing your work. I have the same problem. Constantly transmitting and unable to register. Janne did you find a solution ?

**Comment by vinnyspb** [comment]
You guys probably are aware of Nexa outlets being in 'register' mode only few seconds after they are plugged into the wall - when LED indicator is blinking? Maybe try to change the code to something else and see if it affects somehow maybe?

**Comment by hermanil** [comment]
Thank you for the advice Vinny. Registering works fine with the remote included with the Nexas. Changing code does not make a difference. Still working on it. Could be reverting from Jessie to Wheezy makes a difference

**Comment by hermanil** [comment]
In  order to make this work with my Nexa devices the format argument in line 48 of switch_nexa.py had to be changed from 08b to 026b. Pairing may need 2-3 attempts but once paired, the range and reliability is good.

**Comment by vinnyspb** [comment]
Thanks @hermanil! I initially used correctly chosen transmitter codes (like in the config example: 44756010) and this was automatically decayed into 26 bits. Pushed the fix now.
