### ISSUE TITLE
error usting manual_switch.py

### ISSUE THREAD

**Issue by boerti71** [vinnyspb/nexa-controller-rpi#3]
Hi
manual_switch.py is generating an error message:
>pi@octopi:~/nexa-controller-rpi $ python manual_switch.py on 15 14072974,16
>Traceback (most recent call last):
>  File "manual_switch.py", line 9, in <module>
>    switcher = NexaSwitcher(data_pin=int(sys.argv[2]), transmitter_code=int(sys.argv[3]))
>ValueError: invalid literal for int() with base 10: '14072974,16'

15 = pin, 
14072974 = TransmitterID (is working with arduino)
16 = channel to set on

looking forward to receive your feedback!

**Comment by vinnyspb** [comment]
Usage: on|off data_pin_number transmitter_code

There should be no commas and ‘16’ is not expected.

**Comment by boerti71** [comment]
ok, thanks. probably a stupid question, but how is the transmitter_code defined?
I suppose he includes the Nexa ID(my case 14072974) and the unit number.

Thanks for your support again :-)

**Comment by vinnyspb** [comment]
You have to choose it yourself. Basically choose any number and start the receiver in pairing mode. Then issue “on” command a couple of times with the selected transmitter code. That will make the receiver “remember” your transmitter code.

**Comment by boerti71** [comment]
ok, I understand (almost, soon), according to http://tech.jolowe.se/home-automation-rf-protocols/, the transmitter-code is different for on/off, but for your version do I have to use always the same transmitter-code?

**Comment by vinnyspb** [comment]
Yep, for hardware I used, transmitter code is the same for on/off

**Comment by boerti71** [comment]
ok, I understand, it seems (in my case NEZCR-1500) that the manual_switch.py is sending to short, as I hear only 2 clicks when I teach it, with the Nexa remote it clicks 3 times.


**===>  it works, I thank you for your support!**

**Comment by boerti71** [comment]
nope, my fault, it works:-)
