### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by testbughub** [vinnyspb/nexa-controller-rpi#4]
Hi!

So I just got myself a Nexa WT2, and I'm trying to get this to work. I realize it's a pretty old repo, but I hope you could help me anyway.

I get an "Internal Server Error" when I try to get to the web server.

Error on the Pi;

> 2019-12-28 15:43:57,012  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
> 2019-12-28 15:44:14,146 Exception on / [GET]
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "web_interface.py", line 24, in ini_editor
>     config = Config()
>   File "/root/Downloads/nexa-controller-rpi/controller_config.py", line 23, in __init__
>     self.read_config(file_name)
>   File "/root/Downloads/nexa-controller-rpi/controller_config.py", line 33, in read_config
>     self.EARLIEST_ENABLE_HOUR = int(config.get('TIME', 'EARLIEST_ENABLE_HOUR'))
>   File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
>     raise NoSectionError(section)
> NoSectionError: No section: 'TIME'
> 2019-12-28 15:44:14,154 192.168.0.13 - - [28/Dec/2019 15:44:14] "GET / HTTP/1.1" 500 -

**Comment by vinnyspb** [comment]
Looks like config file doesn't have [TIME] section in it. Have you copied controller_config.ini.example to controller_config.ini and edited accordingly?

**Comment by testbughub** [comment]
Oh, I didn't realize they had to stay. I enabled the TIME section again, and it now works.
Thanks!

**Comment by testbughub** [comment]
Sorry about this, but you wouldn't maybe be able to help me?
I bought a wall switch (just a transmitter), and I'm trying to get the codes it sends, but I can't seem to get anything from it.
Is it even possible to have the Pi as the "hub"?

If I should ask somewhere else, just close this issue.

**Comment by vinnyspb** [comment]
You can in theory get the transmitter code, but you need a receiver hardware for that matter. This project can only behave as a transmitter itself, so it would need to be extended to act as a hub.

**Comment by testbughub** [comment]
I see. Thank you for your quick reply!
